export const types = {
  LOGIN: '[AUTH] LOGIN',
  LOGOUT: '[AUTH] LOGOUT',

  UI_SET_ERROR: '[UI] UI_SET_ERROR',
  UI_REMOVE_ERROR: '[UI] UI_REMOVE_ERROR',
  UI_START_LOADING: '[UI] UI_START_LOADING',
  UI_FINISH_LOADING: '[UI] UI_FINISH_LOADING'
}

